# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Anup Ghatage
tagline:             ""
description:         "Code. Music. Illusions.<br> All kinds of new tech           ...and Butterscotch"
url:                 http://www.ghatage.com
baseurl:             /
gems: [jekyll-paginate]
paginate:            100
paginate_path:	     "/blog/page:num/"

# About/contact
author:
  name:              Anup Ghatage
  url:               https://twitter.com/ghatageanup
  email:             ghatageanup@gmail.com

# Custom vars
version:             1.0.0
